### ISSUE TITLE
Проблема с расписанием

### ISSUE THREAD

**Issue by porot07** [rolling-scopes-school/stage0#16]
https://docs.google.com/spreadsheets/u/0/d/1oM2O8DtjC0HodB3j7hcIResaWBw8P18tXkOl1ymelvE/htmlview#gid=1646898206 - здесь у Basic JS 29-го дедлайн

https://rolling-scopes-school.github.io/stage0/#/stage0/tasks/index - а здесь у вас 15-го марта дедлайн. Поправьте - а то будут недопонимания)

**Comment by irinainina** [comment]
спасибо, поправила
