### ISSUE TITLE
Критерии оценки задания Wildlife

### ISSUE THREAD

**Issue by noche-polar** [rolling-scopes-school/stage0#21]
Добрый день,

Есть предложение добавить дисклеймер, что Критерии оценки и составленный по ним чек-лист являются обязательными, но не исчерпывающими критериями для проверки задания, чтобы разрешить споры, нужно ли оценивать только по Критериям, либо исходя из всего ТЗ (в ТЗ есть пункты, которых в Критериях нет - например, отцентрированность и ширина блока с контентом).

Могу создать Pull request.

Спасибо.

**Comment by Valeria154** [comment]
Добрый день! Оценивать нужно только по Критериям. Если у Вас есть
предложения по остальным пунктам ТЗ, которые не входят в критерии оценки,
пожалуйста делитесь. Буду признательна))))

вт, 16 мар. 2021 г. в 15:58, Alena Kastsiuchyk ***@***.***>:

**Comment by noche-polar** [comment]
Спасибо за Ваш ответ :)

К сожалению, некоторые активисты имеют иное мнение и поощряют других студентов не придерживаться только критериев.
Например, некоторые снимали баллы за
1. Неотцентрированный контент
2. Ширину контентной части не равной 1200px

**Comment by irinainina** [comment]
Вообще-то требования таска должны быть выполнены все и полностью. И если за невыполненные требования снимают баллы, здесь неправы оба - и проверяющий, который не придерживается критериев оценки, и автор таска, который не выполнил требования.
