### ISSUE TITLE
Критерии оценки задания photo filter

### ISSUE THREAD

**Issue by no95typem** [rolling-scopes-school/stage0#29]
Здравствуйте. В критериях есть выражение:
`изображение скачивается в исходном размере +5`
Имелся ввиду, наверное, размер в пикселях? Если так, то "размер" могут многие понять совсем по другому, может быть стоит добавить уточнение?

**Comment by irinainina** [comment]
Привет. В чём ещё измеряют размер изображения, кроме как в пикселях?

**Comment by no95typem** [comment]
Да, Вы правы, в пикселях, но ведь я о другом, возможно многие могут трактовать "размер изображения" как "размер файла изображения" и проверять на соответствие байтов, а не пикселей, что, конечно, будет ошибкой проверяющего, но кто же разбираться то будет? Возможно, кажется притянутым за уши, но на эти мысли меня навел реальный пример такой трактовки.

**Comment by irinainina** [comment]
> Да, Вы правы, в пикселях, но ведь я о другом, возможно многие могут трактовать "размер изображения" как "размер файла изображения" и проверять на соответствие байтов, а не пикселей, что, конечно, будет ошибкой проверяющего, но кто же разбираться то будет? Возможно, кажется притянутым за уши, но на эти мысли меня навел реальный пример такой трактовки

Спасибо, дополнительно указала про размер изображения в пикселях.
