### ISSUE TITLE
Добавление видео материалов в курс

### ISSUE THREAD

**Issue by HalinaPP** [rolling-scopes-school/stage0#5]
Добрый утро! 
Есть предложения по добавлению видео в курс.

Очень полезные видео на первоначальном этапе.
Для понимания как отлавливать ошибки и что происходит в браузере.
Chrome Dev Tools
https://www.youtube.com/watch?v=0sDHMq3x4fA&feature=youtu.be

Для понимая в общем что такое dns, http, https. Второе видео посложнее. Но когла начинается работа с api, у многих вопросы и непонимания есть с CORS. Поэтому общее понимание должно быть.
Network communication
https://www.youtube.com/watch?v=4jA9Nea51T8
https://www.youtube.com/watch?v=_8GoJck9O9Y&feature=youtu.be

**Comment by irinainina** [comment]
Спасибо большое! Добавила видео про Chrome Dev Tools. Более сложное останется для основного потока.
