### ISSUE TITLE
Wildlife

### ISSUE THREAD

**Issue by diman17** [rolling-scopes-school/stage0#9]
В описании к заданию есть пункт: 

- Ширина макета 1440px, ширина контентной части 1200рх. Макет позиционируем по центру с равными отступами по краям. Блокам задаём цвет фона, растягивая их во всю ширину экрана. Блоки Header и Survival - background-color: #02160b, блоки Latest articles и Get notified background-color: #cccccc, блок Footer - background-color: #181617

В критериях оценки данный пункт не упоминается, также как и в форме для проверки задания, из-за чего, на мой взгляд, создается небольшая путаница нужно ли все-таки снижать баллы при отсутствии этого фона.

Предлагаю либо добавить этот пункт в критерии оценки и форму для проверки, либо пометить этот пункт, как необязательный (рекомендуемый).

**Comment by irinainina** [comment]
1. пункт обязательный
2. он не оценивается
я считаю что правы будут как студенты, которые снимут баллы (требование не выполнено) так и те, кто баллы не снимет (в критериях оценки штрафных баллов за этот пункт нет). при этом баллы возможно потеряют только те студенты, которые не выполнили требование, у тех, кто его выполнил, никаких проблем не будет.
